<?php

namespace ContainerFyQhhYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RR0AM_BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rR0AM.B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rR0AM.B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\ModeleRepository', 'getModeleRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ModeleRepository',
        ]);
    }
}
