<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Modele extends \App\Entity\Modele implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null, 16],
        "\0".parent::class."\0".'pays' => [parent::class, 'pays', null, 16],
        "\0".parent::class."\0".'voitures' => [parent::class, 'voitures', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'libelle' => [parent::class, 'libelle', null, 16],
        'pays' => [parent::class, 'pays', null, 16],
        'voitures' => [parent::class, 'voitures', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
