<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLMBTDag\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLMBTDag/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLMBTDag.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLMBTDag\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLMBTDag\App_KernelDevDebugContainer([
    'container.build_hash' => 'LMBTDag',
    'container.build_id' => '9c66f1e9',
    'container.build_time' => 1764420653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLMBTDag');
