<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAlxJb9P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAlxJb9P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAlxJb9P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAlxJb9P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAlxJb9P\App_KernelDevDebugContainer([
    'container.build_hash' => 'AlxJb9P',
    'container.build_id' => '7d4eaaa3',
    'container.build_time' => 1764419879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAlxJb9P');
