<?php

namespace ContainerAlxJb9P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bk9drUBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bk9drUB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bk9drUB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vr' => ['privates', 'App\\Repository\\VoitureRepository', 'getVoitureRepositoryService', true],
        ], [
            'vr' => 'App\\Repository\\VoitureRepository',
        ]);
    }
}
