<?php

namespace ContainerAlxJb9P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4qA6ODService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C4qA6OD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C4qA6OD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\VoitureController::addVoiture' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\VoitureController::delete' => ['privates', '.service_locator.UgYsvL_', 'get_ServiceLocator_UgYsvLService', true],
            'App\\Controller\\VoitureController::listeVoiture' => ['privates', '.service_locator.bk9drUB', 'get_ServiceLocator_Bk9drUBService', true],
            'App\\Controller\\VoitureController::updateVoiture' => ['privates', '.service_locator.UgYsvL_', 'get_ServiceLocator_UgYsvLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\VoitureController:addVoiture' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\VoitureController:delete' => ['privates', '.service_locator.UgYsvL_', 'get_ServiceLocator_UgYsvLService', true],
            'App\\Controller\\VoitureController:listeVoiture' => ['privates', '.service_locator.bk9drUB', 'get_ServiceLocator_Bk9drUBService', true],
            'App\\Controller\\VoitureController:updateVoiture' => ['privates', '.service_locator.UgYsvL_', 'get_ServiceLocator_UgYsvLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VoitureController::addVoiture' => '?',
            'App\\Controller\\VoitureController::delete' => '?',
            'App\\Controller\\VoitureController::listeVoiture' => '?',
            'App\\Controller\\VoitureController::updateVoiture' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VoitureController:addVoiture' => '?',
            'App\\Controller\\VoitureController:delete' => '?',
            'App\\Controller\\VoitureController:listeVoiture' => '?',
            'App\\Controller\\VoitureController:updateVoiture' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
