<?php

namespace ContainerFbjUbL1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7PK0ExpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7PK0Exp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7PK0Exp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ModeleController::add' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController::delete' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController::list' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController::update' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\VoitureController::addVoiture' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\VoitureController::delete' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'App\\Controller\\VoitureController::listeVoiture' => ['privates', '.service_locator.bk9drUB', 'get_ServiceLocator_Bk9drUBService', true],
            'App\\Controller\\VoitureController::updateVoiture' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'App\\Controller\\VoitureController::voituresParModele' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ModeleController:add' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController:delete' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController:list' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\ModeleController:update' => ['privates', '.service_locator.rR0AM.B', 'get_ServiceLocator_RR0AM_BService', true],
            'App\\Controller\\VoitureController:addVoiture' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\VoitureController:delete' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'App\\Controller\\VoitureController:listeVoiture' => ['privates', '.service_locator.bk9drUB', 'get_ServiceLocator_Bk9drUBService', true],
            'App\\Controller\\VoitureController:updateVoiture' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'App\\Controller\\VoitureController:voituresParModele' => ['privates', '.service_locator.sOpJjZi', 'get_ServiceLocator_SOpJjZiService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ModeleController::add' => '?',
            'App\\Controller\\ModeleController::delete' => '?',
            'App\\Controller\\ModeleController::list' => '?',
            'App\\Controller\\ModeleController::update' => '?',
            'App\\Controller\\VoitureController::addVoiture' => '?',
            'App\\Controller\\VoitureController::delete' => '?',
            'App\\Controller\\VoitureController::listeVoiture' => '?',
            'App\\Controller\\VoitureController::updateVoiture' => '?',
            'App\\Controller\\VoitureController::voituresParModele' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ModeleController:add' => '?',
            'App\\Controller\\ModeleController:delete' => '?',
            'App\\Controller\\ModeleController:list' => '?',
            'App\\Controller\\ModeleController:update' => '?',
            'App\\Controller\\VoitureController:addVoiture' => '?',
            'App\\Controller\\VoitureController:delete' => '?',
            'App\\Controller\\VoitureController:listeVoiture' => '?',
            'App\\Controller\\VoitureController:updateVoiture' => '?',
            'App\\Controller\\VoitureController:voituresParModele' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
