<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHMl5LHx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHMl5LHx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHMl5LHx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHMl5LHx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHMl5LHx\App_KernelDevDebugContainer([
    'container.build_hash' => 'HMl5LHx',
    'container.build_id' => 'ee89abe3',
    'container.build_time' => 1762716080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHMl5LHx');
