<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbjUbL1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbjUbL1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFbjUbL1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFbjUbL1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFbjUbL1\App_KernelDevDebugContainer([
    'container.build_hash' => 'FbjUbL1',
    'container.build_id' => 'f19c8f71',
    'container.build_time' => 1764950178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbjUbL1');
