<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'modele_add' => [['libelle', 'pays'], ['libelle' => 'Clio', 'pays' => 'France', '_controller' => 'App\\Controller\\ModeleController::add'], [], [['variable', '/', '[^/]++', 'pays', true], ['variable', '/', '[^/]++', 'libelle', true], ['text', '/modeles/add']], [], [], []],
    'modele_list' => [[], ['_controller' => 'App\\Controller\\ModeleController::list'], [], [['text', '/modeles/list']], [], [], []],
    'modele_update' => [['id'], ['_controller' => 'App\\Controller\\ModeleController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modeles/update']], [], [], []],
    'modele_delete' => [['id'], ['_controller' => 'App\\Controller\\ModeleController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modeles/delete']], [], [], []],
    'app_voiture' => [[], ['_controller' => 'App\\Controller\\VoitureController::listeVoiture'], [], [['text', '/voitures']], [], [], []],
    'add_voiture' => [[], ['_controller' => 'App\\Controller\\VoitureController::addVoiture'], [], [['text', '/addVoiture']], [], [], []],
    'voitureDelete' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture']], [], [], []],
    'voitureUpdate' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::updateVoiture'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateVoiture']], [], [], []],
    'voitures_par_modele' => [[], ['_controller' => 'App\\Controller\\VoitureController::voituresParModele'], [], [['text', '/voitures-par-modele']], [], [], []],
];
