<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG1D22uC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG1D22uC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG1D22uC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG1D22uC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG1D22uC\App_KernelDevDebugContainer([
    'container.build_hash' => 'G1D22uC',
    'container.build_id' => '14f4b33d',
    'container.build_time' => 1762698323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG1D22uC');
